import { useState, useEffect } from 'react'
import { useMutation } from '@tanstack/react-query'
import toast from 'react-hot-toast'
import { useAuthStore } from '../../store/authStore'
import { productsApi, aiApi } from '../../services/api'

const INITIAL_FORM = {
  name: '', sku: '', price: '', cost_price: '', category: '', supplier_id: '',
  min_stock: '5', description: '', unit: 'units', initial_stock: '0'
}

export default function ProductModal({ product, suppliers, onClose, onSaved }) {
  const { user } = useAuthStore()
  const canEditCost = user?.role === 'admin' || user?.role === 'manager'
  
  const isEdit = !!product
  const [form, setForm] = useState(isEdit ? {
    name: product.name || '',
    sku: product.sku || '',
    price: product.price?.toString() || '',
    cost_price: product.cost_price?.toString() || '',
    category: product.category || '',
    supplier_id: product.supplier_id || '',
    min_stock: product.min_stock?.toString() || '5',
    description: product.description || '',
    unit: product.unit || 'units',
    initial_stock: '0',
  } : INITIAL_FORM)
  const [generatingSKU, setGeneratingSKU] = useState(false)

  const mutation = useMutation({
    mutationFn: () => isEdit
      ? productsApi.update(product.id, form)
      : productsApi.create(form),
    onSuccess: () => {
      toast.success(isEdit ? 'Product updated!' : 'Product created!')
      onSaved()
    },
    onError: (err) => toast.error(err.response?.data?.error || 'Save failed'),
  })

  const handleGenerateSKU = async () => {
    if (!form.name) return toast.error('Enter product name first')
    setGeneratingSKU(true)
    try {
      const res = await aiApi.generateSKU(form.name, form.category)
      setForm(f => ({ ...f, sku: res.data.sku }))
      toast.success('SKU generated by AI!')
    } catch {
      toast.error('AI SKU generation failed')
    } finally {
      setGeneratingSKU(false)
    }
  }

  const handleSubmit = (e) => {
    e.preventDefault()
    mutation.mutate()
  }

  return (
    <div className="fixed inset-0 z-50 flex items-center justify-center">
      <div className="absolute inset-0 bg-black/30 backdrop-blur-sm" onClick={onClose} />
      <div className="relative bg-white rounded-2xl shadow-editorial-lg w-full max-w-lg mx-4 max-h-[90vh] overflow-y-auto scrollbar-thin">
        <div className="sticky top-0 bg-white rounded-t-2xl px-6 pt-6 pb-4 border-b border-surface-container-low">
          <div className="flex items-center justify-between">
            <h2 className="text-xl font-bold text-on-surface">{isEdit ? 'Edit Product' : 'Add New Product'}</h2>
            <button onClick={onClose} className="p-2 rounded-lg hover:bg-surface-container-low transition-colors">
              <span className="material-symbols-outlined text-on-surface-variant">close</span>
            </button>
          </div>
        </div>

        <form onSubmit={handleSubmit} className="p-6 space-y-4">
          <div className="grid grid-cols-2 gap-4">
            <div className="col-span-2">
              <label className="block text-xs font-bold text-on-surface-variant uppercase tracking-wider mb-1.5">Product Name *</label>
              <input required value={form.name} onChange={e => setForm({ ...form, name: e.target.value })}
                className="w-full bg-surface-container-low border-none rounded-xl px-4 py-2.5 text-sm focus:ring-2 focus:ring-primary/30 outline-none"
                placeholder="e.g. Wireless Headphones Pro" />
            </div>

            <div>
              <label className="block text-xs font-bold text-on-surface-variant uppercase tracking-wider mb-1.5">SKU</label>
              <div className="flex gap-2">
                <input value={form.sku} onChange={e => setForm({ ...form, sku: e.target.value })}
                  className="flex-1 bg-surface-container-low border-none rounded-xl px-4 py-2.5 text-sm focus:ring-2 focus:ring-primary/30 outline-none font-mono"
                  placeholder="AUTO-GENERATED" />
                <button type="button" onClick={handleGenerateSKU} disabled={generatingSKU}
                  className="px-3 py-2.5 bg-primary-fixed/40 text-primary rounded-xl text-xs font-bold hover:bg-primary-fixed/60 transition-colors disabled:opacity-50 flex-shrink-0"
                  title="Generate SKU with AI">
                  {generatingSKU ? '...' : <span className="material-symbols-outlined text-[16px]">psychology</span>}
                </button>
              </div>
            </div>

            <div>
              <label className="block text-xs font-bold text-on-surface-variant uppercase tracking-wider mb-1.5">Unit Price *</label>
              <div className="relative">
                <span className="absolute left-3 top-1/2 -translate-y-1/2 text-on-surface-variant text-sm font-semibold">₹</span>
                <input required type="number" min="0" step="0.01" value={form.price}
                  onChange={e => setForm({ ...form, price: e.target.value })}
                  className="w-full bg-surface-container-low border-none rounded-xl pl-7 pr-4 py-2.5 text-sm focus:ring-2 focus:ring-primary/30 outline-none"
                  placeholder="0.00" />
              </div>
            </div>

            <div>
              <label className="block text-xs font-bold text-on-surface-variant uppercase tracking-wider mb-1.5">Cost Price</label>
              <div className="relative">
                <span className="absolute left-3 top-1/2 -translate-y-1/2 text-on-surface-variant text-sm font-semibold">₹</span>
                <input type="number" min="0" step="0.01" value={form.cost_price}
                  disabled={!canEditCost}
                  title={!canEditCost ? 'Only managers or admins can edit cost price' : ''}
                  onChange={e => setForm({ ...form, cost_price: e.target.value })}
                  className="w-full bg-surface-container-low border-none rounded-xl pl-7 pr-4 py-2.5 text-sm focus:ring-2 focus:ring-primary/30 outline-none disabled:opacity-50"
                  placeholder="0.00" />
              </div>
            </div>

            <div>
              <label className="block text-xs font-bold text-on-surface-variant uppercase tracking-wider mb-1.5">Category *</label>
              <input required value={form.category} onChange={e => setForm({ ...form, category: e.target.value })}
                className="w-full bg-surface-container-low border-none rounded-xl px-4 py-2.5 text-sm focus:ring-2 focus:ring-primary/30 outline-none"
                placeholder="Electronics, Apparel..." list="cat-list" />
              <datalist id="cat-list">
                {['Electronics', 'Apparel', 'Furniture', 'Accessories', 'Food & Beverage', 'Tools', 'Stationery'].map(c =>
                  <option key={c} value={c} />)}
              </datalist>
            </div>

            <div>
              <label className="block text-xs font-bold text-on-surface-variant uppercase tracking-wider mb-1.5">Supplier</label>
              <select value={form.supplier_id} onChange={e => setForm({ ...form, supplier_id: e.target.value })}
                className="w-full bg-surface-container-low border-none rounded-xl px-4 py-2.5 text-sm focus:ring-2 focus:ring-primary/30 outline-none">
                <option value="">No Supplier</option>
                {suppliers.map(s => <option key={s.id} value={s.id}>{s.name}</option>)}
              </select>
            </div>

            <div>
              <label className="block text-xs font-bold text-on-surface-variant uppercase tracking-wider mb-1.5">Min Stock Alert *</label>
              <input required type="number" min="0" value={form.min_stock}
                onChange={e => setForm({ ...form, min_stock: e.target.value })}
                className="w-full bg-surface-container-low border-none rounded-xl px-4 py-2.5 text-sm focus:ring-2 focus:ring-primary/30 outline-none" />
            </div>

            <div>
              <label className="block text-xs font-bold text-on-surface-variant uppercase tracking-wider mb-1.5">Unit</label>
              <select value={form.unit} onChange={e => setForm({ ...form, unit: e.target.value })}
                className="w-full bg-surface-container-low border-none rounded-xl px-4 py-2.5 text-sm focus:ring-2 focus:ring-primary/30 outline-none">
                {['units', 'kg', 'g', 'liter', 'box', 'pack', 'pair', 'set'].map(u =>
                  <option key={u} value={u}>{u}</option>)}
              </select>
            </div>

            {!isEdit && (
              <div>
                <label className="block text-xs font-bold text-on-surface-variant uppercase tracking-wider mb-1.5">Initial Stock</label>
                <input type="number" min="0" value={form.initial_stock}
                  onChange={e => setForm({ ...form, initial_stock: e.target.value })}
                  className="w-full bg-surface-container-low border-none rounded-xl px-4 py-2.5 text-sm focus:ring-2 focus:ring-primary/30 outline-none" />
              </div>
            )}

            <div className="col-span-2">
              <label className="block text-xs font-bold text-on-surface-variant uppercase tracking-wider mb-1.5">Description</label>
              <textarea value={form.description} onChange={e => setForm({ ...form, description: e.target.value })}
                rows={2} placeholder="Optional product description..."
                className="w-full bg-surface-container-low border-none rounded-xl px-4 py-2.5 text-sm focus:ring-2 focus:ring-primary/30 outline-none resize-none" />
            </div>
          </div>

          <div className="flex gap-3 pt-2">
            <button type="button" onClick={onClose}
              className="flex-1 py-3 bg-surface-container-highest rounded-xl text-sm font-semibold text-on-surface hover:bg-surface-container-high transition-colors">
              Cancel
            </button>
            <button type="submit" disabled={mutation.isPending}
              className="flex-1 py-3 bg-gradient-to-br from-primary-container to-primary text-white rounded-xl text-sm font-semibold editorial-shadow hover:opacity-90 active:scale-95 transition-all disabled:opacity-60">
              {mutation.isPending ? 'Saving...' : isEdit ? 'Save Changes' : 'Add Product'}
            </button>
          </div>
        </form>
      </div>
    </div>
  )
}
